### ISSUE TITLE
Invalid markup type 'rdoc' or markup provider (kramdown) is not registered

### ISSUE THREAD

**Issue by bitaxis** [ctran/annotate_models#230]
Hi.  I have a barebones Rails 4.2.0 application (with only one model and default scaffolding) running on Ruby 2.2.0, and I am having an issue using the ```annotate``` gem along with ```yard``` and ```kramdown```.

Here is relevant snippet from my Gemfile:

```ruby
group :development, :test do
  gem "annotate", "~> 2.6.5"
  gem "kramdown", require: false
  gem "yard"
end
```

I ran ```bundle install```, after which I ran ```annotate```, and got the following output:

```
Annotated (1): Person
```

I put ```--markup markdown --markup-provider kramdown``` into my .yardopts file, and then ran ```yard server -r -p 8809```, browsed to ```http://localhost:8809/```, and got the following error in Terminal:

```
[error]: Invalid markup type 'rdoc' or markup provider (kramdown) is not registered.
```

The browser also displays the following stack trace:

```
undefined method `new' for nil:NilClass
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:101:in `html_markup_rdoc'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:41:in `htmlify'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/templates/default/layout/html/setup.rb:49:in `diskfile'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:355:in `render_section'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:251:in `block (2 levels) in run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `each'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `block in run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:386:in `add_options'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:247:in `run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:269:in `block in yieldall'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:400:in `with_section'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:269:in `yieldall'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/templates/default/layout/html/layout.erb:18:in `_erb_cache_0'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:279:in `erb'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:357:in `render_section'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:251:in `block (2 levels) in run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `each'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `block in run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:386:in `add_options'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:247:in `run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/template.rb:135:in `run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/templates/engine.rb:88:in `render'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/base.rb:143:in `render'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/display_file_command.rb:18:in `run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/base.rb:95:in `call'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/library_command.rb:65:in `call'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/router.rb:135:in `route_docs'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/router.rb:110:in `route'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/display_object_command.rb:12:in `run'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/base.rb:95:in `call'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/commands/library_command.rb:65:in `call'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/router.rb:135:in `route_docs'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/router.rb:142:in `route_index'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/router.rb:102:in `route'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/router.rb:54:in `call'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/yard-0.8.7.6/lib/yard/server/rack_adapter.rb:51:in `call'
/Users/nb/.rvm/gems/ruby-2.2.0@testapp-4.2.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
/Users/nb/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/nb/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/nb/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by ctran** [comment]
I failed to see how this is related to annotate?
