### ISSUE TITLE
Blah is not a class (TypeError)

### ISSUE THREAD

**Issue by leonsp** [ctran/annotate_models#264]
I recently updated my app to Rails 4.2.3, Ruby 2.2.2, and Annotate 2.6.10. Now, when I run annotate, I get this error:

    $ bundle exec annotate
    /Users/my_user/Projects/my_project/app/models/web_console.rb:18:in `<top (required)>': WebConsole is not a class (TypeError)
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `load'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `block in load_file'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:647:in `new_constants_in'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:456:in `load_file'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:354:in `require_or_load'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `each'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `block in eager_load!'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `each'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `eager_load!'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:346:in `eager_load!'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/annotate-2.6.10/lib/annotate.rb:113:in `eager_load'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/gems/annotate-2.6.10/bin/annotate:184:in `<top (required)>'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/bin/annotate:23:in `load'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/bin/annotate:23:in `<main>'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/my_user/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

This is what line 18 of that file looks like:

    # == Schema Information
    #
    # Table name: web_consoles
    #
    #  id               :integer          not null, primary key
    #  name             :string(255)
    #  description      :text(1048576)
    #  priority         :integer
    #  protocol         :string(255)
    #  port             :integer
    #  path             :string(255)
    #  created_at       :timestamp
    #  updated_at       :timestamp
    #  flavour_affinity :string(255)
    #

    # Representation of a link to a know web service on a server
    class WebConsole < ActiveRecord::Base

I'm not sure why it's not recognizing WebConsole as a class.

Note that the annotation that's there is from when the application was using Rails 3.1. I haven't been able to run annotate successfully in some time.

**Comment by leonsp** [comment]
The issue was due to a name conflict with an internal Rails class called WebConsole which is new in Rails 4.x.

After I renamed my WebConsole model, I was able to run Annotate successfully with the following command:

    $ show_foreign_keys=false bundle exec annotate
