### ISSUE TITLE
annotate (2.7.1) throws error (Rails 5.0.0.1)

### ISSUE THREAD

**Issue by rhazegh** [ctran/annotate_models#412]
```
[my_project (master)]$ gem install annotate
Fetching: annotate-2.7.1.gem (100%)
Successfully installed annotate-2.7.1
1 gem installed
[my_project (master)]$ annotate
/Users/my_account/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff2fe0fee58 annotate-2.7.1> (NoMethodError)
	from /Users/my_account/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/my_account/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/my_account/.rvm/gems/ruby-2.3.1@my_project/gems/annotate-2.7.1/bin/annotate:18:in `<top (required)>'
	from /Users/my_account/.rvm/gems/ruby-2.3.1@my_project/bin/annotate:23:in `load'
	from /Users/my_account/.rvm/gems/ruby-2.3.1@my_project/bin/annotate:23:in `<main>'
	from /Users/my_account/.rvm/gems/ruby-2.3.1@my_project/bin/ruby_executable_hooks:15:in `eval'
	from /Users/my_account/.rvm/gems/ruby-2.3.1@my_project/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by zealot128** [comment]
I've solved this by adding annotate to the gemfile and executing with bundle exec annotate ...

**Comment by ryanfox1985** [comment]
Maybe the problem is not related with rails version. If you solved with `bundle exec`I think that is your environment (`rbenv` or `rvm`)
