### ISSUE TITLE
RuntimeError: Unable to add defs to DescriptorPool when using protobufs

### ISSUE THREAD

**Issue by davidmuzi** [ctran/annotate_models#461]
Im not sure this is an issue with 'annotate' or 'google-protobuf'.

Error message
`RuntimeError: Unable to add defs to DescriptorPool: Symtab already has a def named 'CarMessage'`

Stacktrace:
```
  /Users/davidmuzi/Desktop/test/Test/app/models/messages/car_pb.rb:6:in `finalize_to_pool'
  /Users/davidmuzi/Desktop/test/Test/app/models/messages/car_pb.rb:6:in `build'
  /Users/davidmuzi/Desktop/test/Test/app/models/messages/car_pb.rb:6:in `<top (required)>'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:477:in `load'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:477:in `block in load_file'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:662:in `new_constants_in'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:476:in `load_file'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:375:in `block in require_or_load'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies/interlock.rb:11:in `loading'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:37:in `load_interlock'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:358:in `require_or_load'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:336:in `depend_on'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:252:in `require_dependency'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.3/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.3/lib/rails/engine.rb:475:in `each'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.3/lib/rails/engine.rb:475:in `block in eager_load!'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.3/lib/rails/engine.rb:473:in `each'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.3/lib/rails/engine.rb:473:in `eager_load!'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.3/lib/rails/engine.rb:354:in `eager_load!'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/annotate-2.6.5/lib/annotate.rb:109:in `eager_load'
  /Users/davidmuzi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/annotate-2.6.5/bin/annotate:155:in `<top (required)>'
  /Users/davidmuzi/.rbenv/versions/2.2.3/bin/annotate:23:in `load'
  /Users/davidmuzi/.rbenv/versions/2.2.3/bin/annotate:23:in `<top (required)>'
```

Steps to reproduce:
New Rails project, add simple model: `rails g model car make model`
Migrate: `rails db:migrate`
Add `annotate` and run: `bundle exec annotate --ignore-model-subdirects` Works OK
Add and generate a protobuf message:
```
syntax = "proto3";

message CarMessage {
  int32  id    = 1;
  string make  = 2;
  string model   = 3;
}
```

Generated the ruby model:
```
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car.proto
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CarMessage" do
    optional :id, :int32, 1
    optional :make, :string, 2
    optional :model, :string, 3
  end
end

CarMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("CarMessage").msgclass
```

Add requirement to car.rb (ApplicationRecord):
`require './app/models/messages/car_pb.rb'`

Run `annotate` again: FAIL.

Test Project:
[Test.zip](https://github.com/ctran/annotate_models/files/1003033/Test.zip)

**Comment by ctran** [comment]
Thanks for the test project.  I'll try to re-produce this.

**Comment by jdwyah** [comment]
Same issue fwiw.

**Comment by maxforasteiro** [comment]
same issue here too
