### ISSUE TITLE
Not working on Rails 5 on api mode

### ISSUE THREAD

**Issue by wellington1993** [ctran/annotate_models#499]
Hi,

please add support to Rails 5 on Api mode.
I can't run the tasks...

Thanks...

**Comment by ctran** [comment]
Could you be a bit more specific?

**Comment by wellington1993** [comment]
Hi, @ctran 

The gem installations worked, but the actions of annotations generate not working after rake migrate.
i tried to run taks manually but i can't generate annotations.

I'm here if you need more details.

Thanks 👍

**Comment by b264** [comment]
Is there an error message?

**Comment by jgrau** [comment]
I'm running rails 5 in api mode without problems.

**Comment by wellington1993** [comment]
Hi,

@b264 and @jgrau  I will try to use the gem again at Rails 5.
As soon as possible I will copy the messages or comment here the result.

Thanks...

**Comment by hernanvicente** [comment]
Hi,

I can confirm that annotate with rails 5.1.2 is not working, when I run `bundle exec annotate` the result is `Model files unchanged.`

Here the Gemfile code: 

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.2'
# Use sqlite3 as the database for Active Record
gem 'pg'
gem 'puma', '~> 3.7'
gem 'active_model_serializers', '~> 0.10.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate', git: 'https://github.com/ctran/annotate_models.git', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
 
```

**Comment by subakva** [comment]
I just ran into this error. Here's the backtrace:
```
/Users/jason/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- active_support/hash_with_indifferent_access (LoadError)
	from /Users/jason/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/jason/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/jason/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate.rb:10:in `<top (required)>'
	from /Users/jason/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jason/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jason/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/bin/annotate:18:in `<top (required)>'
	from /Users/jason/.rbenv/versions/2.4.2/bin/annotate:23:in `load'
	from /Users/jason/.rbenv/versions/2.4.2/bin/annotate:23:in `<main>'
```

**Comment by subakva** [comment]
It turns out that postgresql wasn't running properly. Once I fixed that, I didn't get the error anymore. I'm not sure why that would trigger a LoadError for `active_support`.
