### ISSUE TITLE
Unable to use annotate with devise (Before process_action callback :authenticate_scope has not been defined)

### ISSUE THREAD

**Issue by tobiasmueller** [ctran/annotate_models#529]
Rails 5.0.1 - annotate 2.7.1

I tried to annotate a new model, but I get an error message.

I think it has to do with the devise gem.

```
annotate --exclude tests,fixtures,factories,serializers
```
Stack trace:
```
/Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :authenticate_scope has not been defined (ArgumentError)
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:637:in `each'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:637:in `block in skip_callback'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:568:in `block in __update_callbacks'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:566:in `reverse_each'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:566:in `__update_callbacks'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:636:in `skip_callback'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:212:in `block (3 levels) in <module:ClassMethods>'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:95:in `block in _insert_callbacks'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:94:in `each'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:94:in `_insert_callbacks'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:211:in `block (2 levels) in <module:ClassMethods>'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:218:in `block (2 levels) in <module:ClassMethods>'
	from /Users/tobiasmueller/code/rubyonrails/anono/app/controllers/custom_devise/registrations_controller.rb:3:in `<class:RegistrationsController>'
	from /Users/tobiasmueller/code/rubyonrails/anono/app/controllers/custom_devise/registrations_controller.rb:1:in `<top (required)>'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `load'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `block in load_file'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:476:in `load_file'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:336:in `depend_on'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:252:in `require_dependency'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/railties-5.0.1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/railties-5.0.1/lib/rails/engine.rb:475:in `each'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/railties-5.0.1/lib/rails/engine.rb:475:in `block in eager_load!'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/railties-5.0.1/lib/rails/engine.rb:473:in `each'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/railties-5.0.1/lib/rails/engine.rb:473:in `eager_load!'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/railties-5.0.1/lib/rails/engine.rb:354:in `eager_load!'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/annotate-2.7.1/lib/annotate.rb:147:in `eager_load'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/gems/annotate-2.7.1/bin/annotate:195:in `<top (required)>'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/bin/annotate:22:in `load'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/bin/annotate:22:in `<main>'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tobiasmueller/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tobiasmueller** [comment]
Solution:
https://github.com/plataformatec/devise/issues/4207
