### ISSUE TITLE
Unable to autoload constant when using custom attribute

### ISSUE THREAD

**Issue by Techbrunch** [ctran/annotate_models#536]
Hello,

I'm currently using the  Rails 5 Attributes API to define a custom type which appears to break annotate.

`/app/models/foo.rb`:
```ruby
class Foo < ApplicationRecord
  attribute :serialized_field, :serialized_php
end
```

`/config/initializers/types.rb`:
```ruby
ActiveRecord::Type.register(:serialized_php, SerializedPHP)
```

`/app/models/attributes/serialized_php.rb`:
```ruby
require 'php_serialize'

class SerializedPHP < ActiveRecord::Type::String
  def type
    :serialized_php
  end

  def cast(value)
    value ? PHP.unserialize(value) : nil
  end

  def serialize(value)
    PHP.serialize(value)
  end
end
```

Stacktrace:

```
/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:511:in `load_missing_constant': Unable to autoload constant SerializedPhp, expected /vagrant/xxx/xxx/app/models/attributes/serialized_php.rb to define it (LoadError)
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:269:in `const_get'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:269:in `block in constantize'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:267:in `each'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:267:in `inject'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:267:in `constantize'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:615:in `get_loaded_model'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:598:in `get_model_class'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:659:in `annotate_model_file'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:646:in `block in do_annotations'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:645:in `each'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:645:in `do_annotations'
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/annotate-2.7.2/bin/annotate:201:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.4.1/bin/annotate:22:in `load'
	from /home/ubuntu/.rbenv/versions/2.4.1/bin/annotate:22:in `<main>'
```

**Comment by 0x01f7** [comment]
* rename `SerializedPHP` to `SerializedPhp`.
* or add

  ```ruby
  ActiveSupport::Inflector.inflections(:en) do |inflect|
    inflect.acronym 'PHP'
  end
  ``` 

  to file `config/initializers/inflections.rb`

**Comment by Techbrunch** [comment]
@0x01f7 Thanks !
