### ISSUE TITLE
annotate fails with 'is not a symbol nor a string error -- dont understand how to fix.  

### ISSUE THREAD

**Issue by joshk6** [ctran/annotate_models#576]
Describe your problem here.
annotate fails after recent migration.  I get the error shown below when i type annotate on the command line.

## Commands

```
/Users/j[xxx]/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.5/lib/active_record/attribute_methods.rb:112:in `method_defined?': QbPurchaseOrder(id: integer, qb_id: integer, po_status: string, doc_number: string, created_qbo: datetime, updated_qbo: datetime, currency: string, po_total: decimal, last_po_total: decimal, vendor_name: string, qb_vendor_id: string, po_charged_off_total: decimal, po_balance: decimal, last_backend_update: datetime, created_at: datetime, updated_at: datetime) is not a symbol nor a string (TypeError)

Here's the beginning of the error stack:

   from /Users/jkramer/.rvm/gems/ruby-2.4.2/gems/annotate-2.7.4/lib/annotate.rb:156:in `eager_load'
        from /Users/jkramer/.rvm/gems/ruby-2.4.2/gems/annotate-2.7.4/bin/annotate:209:in `<top (required)>'
        from /Users/jkramer/.rvm/gems/ruby-2.4.2/bin/annotate:23:in `load'
        from /Users/jkramer/.rvm/gems/ruby-2.4.2/bin/annotate:23:in `<main>'
        from /Users/jkramer/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/jkramer/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'

$ show your commands here.
```
Here is the model 
class QbPurchaseOrder < ApplicationRecord
  has_many :qb_po_line_item, dependent: :destroy
end

Here is schema for the table:
 create_table "qb_purchase_orders", force: :cascade do |t|
    t.integer "qb_id"
    t.string "po_status"
    t.string "doc_number"
    t.datetime "created_qbo"
    t.datetime "updated_qbo"
    t.string "currency", default: "USD"
    t.decimal "po_total", precision: 2
    t.decimal "last_po_total", precision: 2, default: "0"
    t.string "vendor_name"
    t.string "qb_vendor_id"
    t.decimal "po_charged_off_total", default: "0.0"
    t.decimal "po_balance", precision: 2, default: "0"
    t.datetime "last_backend_update"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["last_backend_update"], name: "index_qb_purchase_orders_on_last_backend_update"
    t.index ["qb_id"], name: "index_qb_purchase_orders_on_qb_id"
  end

 ## Version
- annotate version - most recent
- rails version 5.1.5
- ruby version .2.4.2

**Comment by joshk6** [comment]
Sorry, found it error in the dependent model.  f  Tried to delete but can't find a delete.
