### ISSUE TITLE
ruby_parser gem error with declarative_authorization

### ISSUE THREAD

**Issue by marcamillion** [ctran/annotate_models#585]
When I try to annotate my models, it doesn't work.

## Commands

```
$ annotate
/.rvm/gems/ruby-2.3.0@myproject/gems/declarative_authorization-0.5.7/lib/declarative_authorization/development_support/analyzer.rb:9:in `rescue in <top (required)>': Authorization::DevelopmentSupport::Analyzer requires ruby_parser gem (RuntimeError)
	from /.rvm/gems/ruby-2.3.0@myproject/gems/declarative_authorization-0.5.7/lib/declarative_authorization/development_support/analyzer.rb:3:in `<top (required)>'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:234:in `block in load_dependency'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:234:in `load_dependency'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/declarative_authorization-0.5.7/app/controllers/authorization_rules_controller.rb:3:in `<top (required)>'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:469:in `load'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:469:in `block in load_file'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:468:in `load_file'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:353:in `require_or_load'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:313:in `depend_on'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:225:in `require_dependency'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/engine.rb:443:in `each'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/engine.rb:443:in `block in eager_load!'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/engine.rb:441:in `each'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/engine.rb:441:in `eager_load!'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/application/railties.rb:8:in `each'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/application/railties.rb:8:in `all'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/engine.rb:439:in `eager_load!'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/annotate-2.7.1/lib/annotate.rb:147:in `eager_load'
	from /.rvm/gems/ruby-2.3.0@myproject/gems/annotate-2.7.1/bin/annotate:195:in `<top (required)>'
	from /.rvm/gems/ruby-2.3.0@myproject/bin/annotate:22:in `load'
	from /.rvm/gems/ruby-2.3.0@myproject/bin/annotate:22:in `<main>'
	from /.rvm/gems/ruby-2.3.0@myproject/bin/ruby_executable_hooks:15:in `eval'
	from /.rvm/gems/ruby-2.3.0@myproject/bin/ruby_executable_hooks:15:in `<main>'
```

## Version

- annotate version -`2.7.1`.
- rails version - `3.2.22.5`
- ruby version - `2.3.0`
- declarative_authorization - `0.5.7`

What could be causing this and is there a fix for it?

**Comment by ctran** [comment]
The error message says you need "ruby_parser" gem (declarative_authorization).  Try to add that to your Gemfile and run `bundle install` again.
