### ISSUE TITLE
Unable to annotate <model> : can't modify frozen String: "decimal"

### ISSUE THREAD

**Issue by n-rodriguez** [ctran/annotate_models#834]
Describe your problem here.

## Commands

```
nicolas@laptop:~/PROJECTS/concerto$ bin/annotate
Unable to annotate app/models/camping_raw.rb: can't modify frozen String: "decimal"
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:259:in `block in get_schema_info'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:250:in `each'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:250:in `get_schema_info'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:621:in `annotate'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:818:in `annotate_model_file'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:794:in `block in do_annotations'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:793:in `each'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/lib/annotate/annotate_models.rb:793:in `do_annotations'
	/home/nicolas/.anyenv/envs/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/annotate-3.1.1/bin/annotate:31:in `<top (required)>'
	bin/annotate:29:in `load'
	bin/annotate:29:in `<main>'
```

## Version

- annotate annotate-3.1.1
- rails  6.0.3.2
- ruby 2.7.1

**Comment by choilive** [comment]
Do you have `# frozen_string_literal: true` at the top of `camping_raw.rb` or the migration file with the create table..?

**Comment by n-rodriguez** [comment]
Yes

**Comment by choilive** [comment]
Yeah, thats why you're getting the error, it doesnt appear that this gem is string literal friendly, should work if you remove the frozen string literal line.
