### ISSUE TITLE
bundler: failed to load command: annotate

### ISSUE THREAD

**Issue by Rex-am-I** [ctran/annotate_models#916]
After installing the annotate gem via the gemfile method, I ran the following command: 
'bundle exec annotate --models'
I got an error with the following log:

bundler: failed to load command: annotate (/home/xceed/.rbenv/versions/3.0.2/bin/annotate)
/home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/annotate-2.6.5/bin/annotate:152:in `<top (required)>': invalid option: --models (OptionParser::InvalidOption)
Did you mean?  model-dir
        from /home/xceed/.rbenv/versions/3.0.2/bin/annotate:23:in `load'
        from /home/xceed/.rbenv/versions/3.0.2/bin/annotate:23:in `<top (required)>'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `load'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:23:in `run'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/cli.rb:478:in `exec'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /home/xceed/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
        from /home/xceed/.rbenv/versions/3.0.2/bin/bundle:23:in `load'
        from /home/xceed/.rbenv/versions/3.0.2/bin/bundle:23:in `<main>'

I tried using the latest version (v3.1.1) but apparently, that is not compatible with the version of activerecord (v7) required by rails 7 

annotate 2.6.5 and 3.1.1
rails 7
ruby 3

**Comment by willyjie** [comment]
+1

**Comment by Rex-am-I** [comment]
willyjie thanks. I suppose I can live with not specifying models.
